#!/bin/bash
# ============================================================
# HCL Learning Hub — VM Setup & Deployment Script
# Created by: B Raghavendra
# Email: raghavendrab@hcl-software.com
#
# Usage:  sudo bash ai-quest-setup.sh [--repo <github-url>]
# Tested: Ubuntu 22.04 LTS / 24.04 LTS
# ============================================================

set -e  # Exit on any error

# ── Configurable defaults ──────────────────────────────────────────────────────
GITHUB_REPO="${GITHUB_REPO:-https://github.com/raghavendra-bhaskar/Hcl-learning-hub.git}"
INSTALL_DIR="/product/hcl-learning-hub"
APP_PORT="${APP_PORT:-80}"

# ── Colour helpers ─────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}⚠${NC} $*"; }
fail() { echo -e "${RED}✗${NC} $*"; exit 1; }
info() { echo -e "  $*"; }

banner() {
  echo ""
  echo "========================================"
  echo "  $1"
  echo "========================================"
}

# ── Root check ────────────────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  fail "Run this script as root: sudo bash $0"
fi

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    --repo) GITHUB_REPO="$2"; shift 2 ;;
    --port) APP_PORT="$2";    shift 2 ;;
    --dir)  INSTALL_DIR="$2"; shift 2 ;;
    *) warn "Unknown arg: $1"; shift ;;
  esac
done

# ── Banner ────────────────────────────────────────────────────────────────────
clear
echo ""
echo "  ██╗  ██╗ ██████╗██╗     "
echo "  ██║  ██║██╔════╝██║     "
echo "  ███████║██║     ██║     "
echo "  ██╔══██║██║     ██║     "
echo "  ██║  ██║╚██████╗███████╗"
echo "  ╚═╝  ╚═╝ ╚═════╝╚══════╝"
echo ""
echo "  HCL Learning Hub — Deployment Setup"
echo "  Repo: $GITHUB_REPO"
echo "  Dir:  $INSTALL_DIR"
echo "  Port: $APP_PORT"
echo ""

# ── Step 1: System packages ───────────────────────────────────────────────────
banner "Step 1: System Update & Base Packages"

chmod -x /etc/update-motd.d/* 2>/dev/null || true

apt-get update -y
apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    git \
    jq \
    openssl

ok "Base packages installed"

# ── Step 2: Docker ────────────────────────────────────────────────────────────
banner "Step 2: Docker & Docker Compose"

if command -v docker &>/dev/null; then
  ok "Docker already installed: $(docker --version)"
else
  info "Installing Docker CE..."

  mkdir -p /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null

  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

  service docker start
  ok "Docker installed: $(docker --version)"
fi

# Verify docker compose plugin
if ! docker compose version &>/dev/null; then
  apt-get install -y docker-compose-plugin
fi
ok "Docker Compose: $(docker compose version --short)"

# ── Step 3: Application directory ─────────────────────────────────────────────
banner "Step 3: Application Directory"

mkdir -p /product

if [ -d "$INSTALL_DIR/.git" ]; then
  warn "Directory $INSTALL_DIR already exists — pulling latest changes..."
  cd "$INSTALL_DIR"
  git pull
  ok "Repository updated"
else
  info "Cloning from $GITHUB_REPO..."
  git clone "$GITHUB_REPO" "$INSTALL_DIR"
  cd "$INSTALL_DIR"
  ok "Repository cloned to $INSTALL_DIR"
fi

# ── Step 4: Environment configuration ─────────────────────────────────────────
banner "Step 4: Environment Configuration"

SERVER_IP=$(hostname -I | awk '{print $1}')

if [ -f "$INSTALL_DIR/.env" ]; then
  warn ".env already exists — skipping generation (edit manually if needed)"
else
  info "Generating .env from .env.docker template..."

  DB_PASS=$(openssl rand -hex 16)
  JWT_SECRET=$(openssl rand -hex 32)

  cat > "$INSTALL_DIR/.env" << EOF
# HCL Learning Hub — Auto-generated by ai-quest-setup.sh on $(date)
# Edit this file to customise the deployment.

# ── Database ──────────────────────────────────────────────────────────────────
DB_PASSWORD=${DB_PASS}

# ── Application ───────────────────────────────────────────────────────────────
FRONTEND_ORIGIN=http://${SERVER_IP}
HTTP_PORT=${APP_PORT}

# ── Local Admin ───────────────────────────────────────────────────────────────
ADMIN_USERNAME=admin
ADMIN_PASSWORD=Admin@HCL2026!

# JWT signing secret — keep this private
JWT_SECRET=${JWT_SECRET}
EOF

  chmod 600 "$INSTALL_DIR/.env"
  ok ".env generated (DB password and JWT secret auto-randomised)"
fi

# ── Step 5: Build and start ───────────────────────────────────────────────────
banner "Step 5: Build & Start Containers"

cd "$INSTALL_DIR"

info "Building Docker images (this may take 3–5 minutes on first run)..."
docker compose up -d --build

ok "Containers started"

# ── Step 6: Wait for healthy state ────────────────────────────────────────────
banner "Step 6: Health Check"

info "Waiting for services to become healthy..."
TIMEOUT=120
ELAPSED=0

while [ $ELAPSED -lt $TIMEOUT ]; do
  API_STATUS=$(docker compose ps api --format json 2>/dev/null | jq -r '.[0].Health // "unknown"' 2>/dev/null || echo "unknown")
  if [ "$API_STATUS" = "healthy" ]; then
    ok "API service is healthy"
    break
  fi
  sleep 5
  ELAPSED=$((ELAPSED + 5))
  info "Still waiting... ($ELAPSED/${TIMEOUT}s) — API status: $API_STATUS"
done

if [ $ELAPSED -ge $TIMEOUT ]; then
  warn "Health check timed out — containers may still be starting. Check: docker compose logs api"
fi

# Quick HTTP check
sleep 2
if curl -sf "http://localhost:${APP_PORT}/" > /dev/null 2>&1; then
  ok "HTTP endpoint responding on port ${APP_PORT}"
else
  warn "HTTP check failed — nginx may need a moment. Try: curl -I http://localhost:${APP_PORT}/"
fi

# ── Step 7: File limit tuning (same as ccs-new-vm-setup.sh) ──────────────────
banner "Step 7: OS Tuning"

grep -q 'fs.file-max' /etc/sysctl.conf 2>/dev/null || {
  echo '* soft nofile 1048576'     | tee -a /etc/security/limits.conf > /dev/null
  echo '* hard nofile 1048576'     | tee -a /etc/security/limits.conf > /dev/null
  echo 'fs.inotify.max_user_watches=1048576' | tee -a /etc/sysctl.conf > /dev/null
  echo 'fs.file-max=2097152'                 | tee -a /etc/sysctl.conf > /dev/null
  sysctl -p > /dev/null 2>&1
  ok "OS file limit tuning applied"
}

# ── Summary ───────────────────────────────────────────────────────────────────
banner "Setup Complete!"
echo ""
echo -e "  ${GREEN}Application URL${NC}   http://${SERVER_IP}:${APP_PORT}"
echo -e "  ${GREEN}Admin Login${NC}       admin / Admin@HCL2026!"
echo -e "  ${GREEN}Install Directory${NC} ${INSTALL_DIR}"
echo ""
echo "  Next steps:"
echo "  1. Open http://${SERVER_IP}:${APP_PORT} in your browser"
echo "  2. Log in as admin / Admin@HCL2026!  (change password immediately)"
echo "  3. Go to Admin → Authentication Realm → configure your Okta SSO"
echo "  4. Go to Admin → Okta Users → click 'Sync Managers from Okta'"
echo ""
echo "  Useful commands:"
echo "    docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f      # live logs"
echo "    docker compose -f ${INSTALL_DIR}/docker-compose.yml restart       # restart all"
echo "    docker compose -f ${INSTALL_DIR}/docker-compose.yml pull && \\"
echo "      docker compose -f ${INSTALL_DIR}/docker-compose.yml up -d --build  # update"
echo ""
echo "  Secrets are stored in: ${INSTALL_DIR}/.env"
echo "  Database data lives in Docker volume: ai-quest_postgres_data"
echo ""
echo "========================================"
